services:
  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - app/core/.env
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/

  oos-fastapi-backend:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: oos-fastend
    restart: unless-stopped
    ports:
      - '80:8000'
    volumes:
      - .:/home/pre-oos/oos