services:
  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - app/core/.env
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache/:/data/

  redis-test:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel debug

  database-test:
    image: 'postgres:alpine'
    container_name: postgres_test
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - app/core/.env

  cf-fastapi-backend:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: cf-fastend
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - '80:8000'
    volumes:
      - .:/home/pre-cf/cf