services:
  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - app/core/.env
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/
    deploy:
      resources:
        limits:
          memory: 250M
