services:
  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - app/core/.env
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/
    deploy:
      resources:
        limits:
          memory: 250M

  cf-fastapi-backend:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: cf-fastend
    restart: unless-stopped
    ports:
      - '80:8000'
    expose:
      - 80
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./logs/:/home/logs/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --workers 3